spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sns?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

