spring:
  profiles: local

datasource:
  master:
    name: master
    url: jdbc:mysql://34.64.119.222/sns?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  slave:
    slave1:
      name: slave1
      url: jdbc:mysql://127.0.0.1:1111/sns?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
      username: root
      password: 1234



